using geopandas and shapely package to calculate whether there are intersections between bbox and sentinel SAFE file.
isce-framework/isce2 pull request #216
Opened 2020-12-31 03:18 UTC by ranneylxr

Using geopandas and shapely package to calculate whether there are intersections between bbox and sentinel SAFE file.
And remove "import geopandas and shapely" part into generate_geopolygon function.

2020-12-31 03:39 UTC, piyushrpt commented
Just noting that introduces a new dependency on geopandas. The same can be done with `polygon1.intersects(polygon2)` in shapely?

2021-01-02 03:30 UTC, yunjunz requested changes
Thank you @ranneylxr for improving this. I would second @piyushrpt's suggestion on removing `geopandas` as it seems like just using shapely should be enough. [Here](https://gis.stackexchange.com/questions/90055/finding-if-two-polygons-intersect-in-python) is another similar topic on StackExchange. Otherwise, adding a new dependency would result in quite some changes on the installation side.

2021-01-04 07:19 UTC, ranneylxr commented
Hi @piyushrpt and @yunjunz . Thank you for your valuable suggestions. Now the script only uses shapely package. Please check.

2021-01-04 18:59 UTC, rtburns-jpl commented on contrib/stack/topsStack/stackSentinel.py
> +    return bb_polygon
I think using a list comprehension makes this a bit simpler
```suggestion
    points = [Point(bbox[i][0], bbox[i][1]) for i in range(4)]
    return Polygon([(p.coords.xy[0][0], p.coords.xy[1][0]) for p in points])
```

2021-01-06 06:54 UTC, yunjunz commented
Since `matplotlib.path.Path` is not used anymore, could you please also remove [stackSentinel.py#L14-L18](https://github.com/isce-framework/isce2/blob/main/contrib/stack/topsStack/stackSentinel.py#L14-L18)?

2021-01-06 07:24 UTC, yunjunz approved these changes
Looks good and clean. Thank you @ranneylxr.

2021-01-06 17:00 UTC, hfattahi approved these changes
LGTM. Thank you.

2021-01-06 21:19 UTC, merged